[mypy]
strict = True
python_version = 3.11
files = src
plugins = pydantic.mypy

[mypy-langgraph.*]
ignore_missing_imports = True

[mypy-langgraph_checkpoint.*]
ignore_missing_imports = True

[mypy-dspy.*]
ignore_missing_imports = True

[mypy-respx.*]
ignore_missing_imports = True
